### ISSUE TITLE
Be able to wait for a Immortal thread to finish.

### ISSUE THREAD

**Issue by jfischoff** [feuerbach/immortal#1]
For graceful shutdown, I wait for threads to finish in my servers main loop. I would like to do the same with Immortal threads.

I changed the definition to 

``` haskell
data Thread = Thread ThreadId (IORef Bool) (TMVar ())
```

and added the function 

``` haskell
wait :: Thread -> IO ()
wait (Thread _ _ finished) = atomically $ takeTMVar finished >> putTMVar finished ()
```

Should I put together a pull request?

**Comment by feuerbach** [comment]
For the record, this was merged a while ago https://hackage.haskell.org/package/immortal-0.2.2/docs/Control-Immortal.html#v:wait
