### ISSUE TITLE
Reupload Haddocks to Hackage

### ISSUE THREAD

**Issue by stites** [feuerbach/immortal#6]
I just noticed that the hackage readme example (for both [v0.2.2][022] and [v0.2][02]) references `System.Immortal` as the main example, while immortal's main module has always been at `Control.Immortal`. So I think this means that the haddocks just need to be re-uploaded? I'm a little fuzzy on how this would work.

[022]:https://hackage.haskell.org/package/immortal-0.2.2
[02]:https://hackage.haskell.org/package/immortal-0.2

**Comment by feuerbach** [comment]
Thanks for the notice, should be fixed now.
