### ISSUE TITLE
Replace `MonadBaseControl` with `MonadUnliftIO`

### ISSUE THREAD

**Issue by mitchellwrosen** [feuerbach/immortal#7]
Hi, would you accept a patch that replaces the dependency on `monad-control` with `unliftio-core`? (`MonadBaseControl m` -> `MonadUnliftIO m`).

The docs for `immortal` read:

> The monadic «state» (captured by the `MonadBaseControl` instance) will be preserved if the computation terminates normally, and reset when the exception is thrown, so be cautious when `m` is stateful. It is completely safe, however, to instantiate m with something like `ReaderT conf IO` to pass configuration to the new thread.

which is the problem `MonadUnliftIO` is meant to solve.

**Comment by feuerbach** [comment]
Yes, soounds good.
